export const FETCH_POSTS = 'FETCH_POSTS'
export const CREATE_POST = 'CREATE_POST'

export const LOGIN = 'LOGIN'
export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION'
export const USER_DETAILS = 'USER_DETAILS'
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE'
export const USER_OPEN_DETAILS = 'USER_OPEN_DETAILS'
export const USER_BASIC_DETAILS = 'USER_BASIC_DETAILS'
